### ISSUE TITLE
Fighting Wordpress

### ISSUE THREAD

**Issue by flaviobarros** [dokku-alt/dokku-alt#121]
I have been fighting with wordpress installation, and that happens because wordpress isn't stateless. So, i was digging around and found the octohost project, another docker powered mini PaaS .

I found this recipe to install Wordpress https://github.com/octohost/wordpress 

Can i do something like that with dokku-alt?

**Comment by romaninsh** [comment]
Hi All.

I've done some work on creating a good container for stable wordpress with aim to use it in production sites. You can find my work here along with all instructions:

https://github.com/romaninsh/docker-wordpress

I've tried to keep it simple, yet flexible and usable. I hope this is helpful.
