### ISSUE TITLE
Intstall packages in deploy container

### ISSUE THREAD

**Issue by misteral** [dokku-alt/dokku-alt#147]
Happy new year!

My Rails app use some additional packages:
libav-tools 
lame
mp3gain

how i can install it in deploy container?

**Comment by fabiofumarola** [comment]
You can connect to the container via 
> dokku exec <container_name> bash 
and then you should have a shell. Otherwise you can use a Dockerfile in your source project and install the deps.

**Comment by misteral** [comment]
Thanks @fabiofumarola.
If i use Dockerfile in my source, packages will be installed after deploy and saved into container ?

**Comment by fabiofumarola** [comment]
What I found is that if you add a Dockerfile in the source of the project, as described in the doc, it will be deployed with the app. However for a ruby based app it should use the [ruby buildstep conf](https://github.com/progrium/buildstep#adding-buildpacks). So
1. you can try to add a dockerfile with your conf and see if it works 
or 
2. you can deploy the container and log into using docker
   - docker ps <-- to get the id of the deployed container
   - docker exec -it <container_id> /bin/bash

after that you can log in. I tried to use dokku exec <app_name> /bin/bash but it does not work.
Let me know
Cheers

Fabio

**Comment by misteral** [comment]
Thanks Fabio, for your time!
What i do:
Login as root 
```
sudo docker run -t -i ayufan/dokku-alt-buildstep:cedar-14 /bin/bash
```
install packages
make the docker commit 
``` 
sudo docker commit -m="Added my packages" -a="Al Bobrov" a49a2330ffc5 ayufan/dokku-alt-buildstep:cedar-14
```
this resolve my problem, may be is not right way.

**Comment by fabiofumarola** [comment]
Actually I faced the same problem as you. I have investigated more especially considering that I'm totally new to this problem. In my understanding (tell me if you are in accord) it is possible to fork a buildstep and use it in your project.
Let explain myself. 

1. There is the [dokku-alt buildstep](https://github.com/dokku-alt/progrium-buildstep-dockerfiles) that you can fork
2. you can create your buildstep and install all the library that you need, or if you have heavy tar to load just for it
3. you can edit the forked buildstep, that is its Dockerfile
4. Setup the docker file and add the path to your new buildstep in the git folder of your project

>[from dokku-alt buildpack doc](https://github.com/dokku-alt/progrium-buildstep-dockerfiles). Custom buildpacks can be installed by committing a file in the root of your git repository named .env This file should contain a line export BUILDPACK_URL=<repository> specifying the git repository providing the buildpack.

And now there is the part which is not clear to me
 > If your buildpack needs extra packages these can be installed by the buildpack using bin/compile.

**Final remark**. What I found is that it is quite frequent create [your own buildstep on heroku](https://devcenter.heroku.com/articles/third-party-buildpacks#third-party-buildpacks)

It would be good to have the possibility to specify the buildstep name during deploy. I'll tell you when I have more insight.
What do you think?

**Comment by fabiofumarola** [comment]
finally I cloned the original buildstep https://github.com/fabiofumarola/progrium-buildstep-dockerfiles

**Comment by misteral** [comment]
Yes, this is great solution!
