### ISSUE TITLE
apt-get update fails because of dokku alt

### ISSUE THREAD

**Issue by dfurber** [dokku-alt/dokku-alt#151]
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/dokku-alt.github.io_dokku-alt_en
E: The package lists or status file could not be parsed or opened.

When I look at /var/lib/apt/lists/dokku-alt.github.io_dokku-alt_en, I see HTML from GitHub about a page not being there but may take up to 30 minutes.

**Comment by sportsy** [comment]
Having the same issue as well :(

**Comment by ayufan** [comment]
I did clean up gh-pages. It should fix your issues.

It should be sufficient to do:
    apt-get update -y

But if not, please:
    rm -rf /var/lib/apt/lists/dokku-alt.github.io_dokku-alt_*

Thanks!

**Comment by sportsy** [comment]
Totally helped! Thanks!
