### ISSUE TITLE
Locked Container, Can't Deploy or Rebuild

### ISSUE THREAD

**Issue by sportsy** [dokku-alt/dokku-alt#152]
I upgraded my dokku-alt and upgraded all of my other dependencies, when I try to deploy to one of our containers, 

All I ever see is:

=====> apollo is currently locked. We will wait for other process to finish.

There is also quite a few rebuild processes happening:

```
dokku     9868  0.0  0.1  11360  1736 ?        S    04:17   0:00 bash /usr/local/bin/dokku release:locked apollo
dokku     9949  0.0  0.1 266468  1728 ?        Sl   04:17   0:00 pluginhook pre-release apollo
dokku     9951  0.0  0.1  11132  1460 ?        S    04:17   0:00 /bin/bash /var/lib/dokku-alt/plugins/dokku-mongodb/pre-release apollo
dokku     9957  0.0  0.1  11344  1692 ?        S    04:17   0:00 bash /usr/local/bin/dokku mongodb:link apollo db
dokku    10024  0.0  0.1  11372  1756 ?        S    04:17   0:00 /bin/bash /var/lib/dokku-alt/plugins/dokku-mongodb/commands mongodb:link apollo db
dokku    10110  0.0  0.0  11380   956 ?        S    04:17   0:00 /bin/bash /var/lib/dokku-alt/plugins/dokku-mongodb/commands mongodb:link apollo db
dokku    10119  0.0  0.1  11360  1736 ?        S    04:17   0:00 bash /usr/local/bin/dokku release apollo
dokku    10139  0.0  0.0   5900   356 ?        S    04:17   0:00 flock /home/dokku/apollo/build.lock dokku release:locked apollo
```

I can delete the container, but on every fresh push, i'm still receiving the same problem. 

Thanks!

**Comment by ayufan** [comment]
What did happen?

**Comment by sportsy** [comment]
Not really sure. I just destroyed the instance on EC2 and re-created all of our docker containers. I couldn't end up getting past the lock anytime i tried to deploy or rebuild.

**Comment by barmmie** [comment]
it appears Dokku locks by creating an empty hidden file:
/home/dokku/app/.build.lock
I simply deleted this file and I was able to deploy again.
