### ISSUE TITLE
installation fails due to 404 results for dokku-alt.github.io_dokku-alt_en

### ISSUE THREAD

**Issue by fruitl00p** [dokku-alt/dokku-alt#157]
During the default installation the apt-get update fails with;
```
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/dokku-alt.github.io_dokku-alt_en
E: The package lists or status file could not be parsed or opened.
```

Seems the public dokku-alt.github.io is returning a 404 ?

**Comment by ValkyrieUK** [comment]
I'm also getting this

**Comment by seaneking** [comment]
Me too. Worked fine installing it elsewhere a week or so ago.

**Comment by ayufan** [comment]
GitHub most likely changed how it serves gh-pages (pages not found: 404). It's late today. I'll push final fix for this tomorrow.

**Comment by ayufan** [comment]
Can you check now?

First remove problematic file and later do apt-get update.

**Comment by sedouard** [comment]
@ayufan I had the same problem as the issue stated yesterday. deleted the bad files (basically github 404 html pages) and the install seems to be going smoothly now.

Thanks!

**Comment by ValkyrieUK** [comment]
Yup deleted bad files, did `apt-get update` and retried :+1: I think this can be closed now.

**Comment by fruitl00p** [comment]
Will reinstall the server to switch from temporary dokku back to the intended dokku-alt ... I expect it works so i'll close the issue and re-open if need be.. (which i don't expect)

**Comment by fruitl00p** [comment]
It seems it broke again?

**Comment by romaninsh** [comment]
Here is related ticket: https://github.com/dokku-alt/dokku-alt/issues/151#issuecomment-69260234

**Comment by rcarmo** [comment]
This is still broken for me. What is the right URL to list in /etc/apt/sources.list.d/dokku-alt.list ?

**Comment by romaninsh** [comment]
Deleting those files helped me. Dokku-alt is still being updated properly.
