### ISSUE TITLE
Cannot start container: failed to find the cgroup root

### ISSUE THREAD

**Issue by rcreasey** [dokku-alt/dokku-alt#171]
Did the usual install of the dokku-alt service in docker setup and am getting the following on a freshly pushed application:

```
remote: time="2015-01-25T19:42:06Z" level="fatal" msg="Error response from daemon: Cannot start container 60376a0de88c81316233f047c3bb4b70814cfa8a046d63fd1664677837075a30: failed to find the cgroup root"
```

I've tried multiple buildpacks, but this seems to be an issue inherent to the actual dokku-alt image and is possibly related to https://github.com/docker/docker/issues/8791, but none of those steps have fixed anything.

I'm currently running: 
```
ayufan/dokku-alt     latest              acefbab5e3fa        4 weeks ago         472.9 MB
```

Any idea on what could be the issue?

**Comment by rcreasey** [comment]
Realized I had a 4 week old image, just pulled latest:

```
ayufan/dokku-alt     latest              a49ae20643e2        2 weeks ago         473 MB
```

And it's still occurring.

Any suggestions?  @ayufan?

**Comment by rcreasey** [comment]
I have installed on a fresh ubuntu 14.04 with docker 1.4.1 and this is no longer an issue.  Closing.

**Comment by jaybuff** [comment]
@rcreasey it's a race condition and this is a dup of docker/docker#8791
