### ISSUE TITLE
Install without sinatra

### ISSUE THREAD

**Issue by RomkeVdMeulen** [dokku-alt/dokku-alt#177]
Is it possible to install dokku-alt without gettin ruby or sinatra on my host system?

**Comment by romaninsh** [comment]
I think it's needed only for install script, which only adjusts config and imports ssh key and I support the idea of removing ruby dependency, but we need to think about the new workflow.

In theory we don't need key and we can ask user to enter domain in terminal. 

See https://github.com/dokku-alt/dokku-alt/tree/master/contrib
