### ISSUE TITLE
Running on Debian Wheezy?

### ISSUE THREAD

**Issue by mc0e** [dokku-alt/dokku-alt#179]
I see that the README.md file clearly states Ubuntu 14.04, but for a server where not everything will be run through dokku. I'd like to stick with Debian if possible.

Has anyone tried to make this work?  What are the issues?

I know there are some issues to work out with the kernel version on Debian wheezy in order to use docker.  That's covered at http://docs.docker.com/installation/debian/ .

Blindly running the install script, I get as far as trying to `apt-get install -y dokku-alt ruby ruby-sinatra`, which gets me

    The following packages have unmet dependencies:
     dokku-alt : Depends: linux-image-extra-virtual but it is not installable

What's in `linux-image-extra-virtual` that's needed?  Is it just a case of working out the right package names and rolling a debian version of the package, or is there more to it than that?

Looking on an Ubuntu system, it appears that this is a transitional package depending on linux-image-generic.  Is this really necessary?

What else?  Is it worth me going down this rabbit hole, or has someone already been there and found a dead end?

**Comment by ayufan** [comment]
Wheezy has too old packages. You can always run it in docker container:
https://github.com/dokku-alt/dokku-alt#dokku-alt-as-service-in-docker-container-beta



On Tue, Feb 3, 2015 at 11:37 AM, mc0e <notifications@github.com> wrote:

> I see that the README.md file clearly states Ubuntu 14.04, but for a
> server where not everything will be run through dokku. I'd like to stick
> with Debian if possible.
>
> Has anyone tried to make this work? What are the issues?
>
> I know there are some issues to work out with the kernel version on Debian
> wheezy in order to use docker. That's covered at
> http://docs.docker.com/installation/debian/ .
>
> Blindly running the install script, I get as far as trying to apt-get
> install -y dokku-alt ruby ruby-sinatra, which gets me
>
> The following packages have unmet dependencies:
>  dokku-alt : Depends: linux-image-extra-virtual but it is not installable
>
> What's in linux-image-extra-virtual that's needed? Is it just a case of
> working out the right package names and rolling a debian version of the
> package, or is there more to it than that?
>
> Looking on an Ubuntu system, it appears that this is a transitional
> package depending on linux-image-generic. Is this really necessary?
>
> What else? Is it worth me going down this rabbit hole, or has someone
> already been there and found a dead end?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/179>.
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu
