### ISSUE TITLE
Create an IRC room

### ISSUE THREAD

**Issue by josegonzalez** [dokku-alt/dokku-alt#180]
Please create an IRC room for #dokku-alt. We occasionally get questions on dokku-alt specific stuff in #dokku on freenode, and we're unable to handle them as the projects have diverged quite a bit.

As an example, our zero-downtime implementations are quite different at this point, and I just had a question asked about yours. Ideally they aren't, and we can support your users, but that isn't the case :(

**Comment by akoenig** [comment]
Definitely a good idea :+1:

**Comment by ayufan** [comment]
Let's start with gitter.im. I'll later prepare synchronization between IRC channel and Gitter: https://gitter.im/dokku-alt/dokku-alt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
