### ISSUE TITLE
changing php buildpack from existing app fails

### ISSUE THREAD

**Issue by thiver** [dokku-alt/dokku-alt#182]
I have an php application running on the latest stable dokku + the default php buildpack.
When I want to change the buildpack with a .env file (to the latest heroku php buildpack), the push fails.

If I create a new app, the push succeeds without problems.

**Comment by theikkila** [comment]
Same is happening with any buildpack change in existing app, so this is not only php-buildpack related issue.

**Comment by ayufan** [comment]
More info please how to reproduce the issue?

**Comment by thiver** [comment]
0. Create a php app - mine had an empty composer file, an index.php and a Procfile with nginx

0. Deploy and start it with the default buildpack

0. Place an .env file with export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php.git
0. Redeploy the app, the update will fail

If you deploy an app for the first time with a custom buildpack, it works. But when you update the same app again, it seems to fail too. It seems custom buildpacks only work on application "creation".

**Comment by ayufan** [comment]
By .env file you mean the file in projects repository?

**Comment by thiver** [comment]
indeed

**Comment by ayufan** [comment]
Ok. I'll test that. Give ma a few moments.

On Fri, Feb 20, 2015 at 12:03 PM, thiver <notifications@github.com> wrote:

> indeed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/182#issuecomment-75221616>.
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by ayufan** [comment]
I did test it and it works for me. Maybe you can show some log how it works for you?

**Comment by thiver** [comment]
With DOKKU_TRACE enabled:

```bash
-----> Fetching custom buildpack
remote: ++ docker wait bcabf58177bb89b04a565c35ffe08aef2651875114086341f3a45826bf462a92
remote: + test 128 -eq 0
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
+++ [[ -z /home/dokku ]]
+++++ dirname /var/lib/dokku-alt/plugins/htpasswd/commands
++++ cd /var/lib/dokku-alt/plugins/htpasswd
++++ pwd
+++ CWD=/var/lib/dokku-alt/plugins/htpasswd
+ case "$1" in
+ exit 10
+++ [[ -z /home/dokku ]]
+++++ dirname /var/lib/dokku-alt/plugins/nginx-vhosts/commands
++++ cd /var/lib/dokku-alt/plugins/nginx-vhosts
++++ pwd
+++ CWD=/var/lib/dokku-alt/plugins/nginx-vhosts
+ case "$1" in
+ exit 10
+++ [[ -z /home/dokku ]]
+++++ dirname /var/lib/dokku-alt/plugins/ssl/commands
++++ cd /var/lib/dokku-alt/plugins/ssl
++++ pwd
+++ CWD=/var/lib/dokku-alt/plugins/ssl
+ case "$1" in
+ exit 10
To dokku@ip:appname
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@ip:appname'
```

**Comment by thiver** [comment]
Using a fork of the buildpack solved the problem.
Too many unauthenticated requests to the heroku repository perhaps?

**Comment by ayufan** [comment]
Thanks. I did try to find a error, but not managed to do so :(

**Comment by thiver** [comment]
Found the real problem: There has to be a newline after the export line, if there is no newline, the push fails on the custom buildpack.

**Comment by ayufan** [comment]
Nice. Will try.

**Comment by ayufan** [comment]
It's fixed. It will be pushed as beta once this finishes: https://drone.ayufan.eu/github.com/dokku-alt/dokku-alt/master/1ee5f7c56d436a295eda4d2a3d074e9697911653
