### ISSUE TITLE
config_styled_hash in the config plugin affects env-vars with an = in the value

### ISSUE THREAD

**Issue by davidpelaez** [dokku-alt/dokku-alt#184]
https://github.com/dokku-alt/dokku-alt/blob/a8f318ce5b24b11f035537af6fcb3cb97685f9e5/plugins/config/commands#L28 introduces a bug affecting environment variables with an `=`, consider this output for `pluginhook env-vars "$APP"`:

```
XYZ=ABC=
```

If you pipe that through the afore mentioned line note the altered location of the colon

```
$ echo 'XYZ=ABC=' | sed 's/^\(.*\)=/\1:=/g' | column -t -s '='
XYZ  ABC:
```

This is naturally a weird case, but if for instance I have an app token in AWS with an `=`, that would happen.

My solution is to change the spacer in the columns to something different than = and making the replacement only once. I use `>>>` as as spacer since that's a very unlikely env var value (unless you know something different!):

```
$ echo 'XYZ=ABC=' | sed 's/^\([^=]*\)=/\1:>>>/' | column -t -s '>>>'
XYZ:  ABC=
```

In this case the `=` is preserved in the env var value. I'll check if this solves a bug I found and update the comment afterwards and possibly send a PR.

**Comment by ayufan** [comment]
Thanks. Let me know.

On Sat, Feb 14, 2015 at 12:36 AM, David Pelaez <notifications@github.com>
wrote:

>
> https://github.com/dokku-alt/dokku-alt/blob/a8f318ce5b24b11f035537af6fcb3cb97685f9e5/plugins/config/commands#L28
> introduces a bug affecting environment variables with an =, consider this
> output for pluginhook env-vars "$APP":
>
> XYZ=ABC=
>
> If you pipe that through the afore mentioned line note the altered
> location of the colon
>
> $ echo 'export XYZ=ABC=' | sed 's/^\(.*\)=/\1:=/g' | column -t -s '='
> export XYZ  ABC:
>
> This is naturally a weird case, but if for instance I have an app token in
> AWS with an =, that would happen.
>
> My solution is to change the spacer in the columns to something different
> than = and making the replacement only once. I use >>> as as spacer since
> that's a very unlikely env var value (unless you know something different!):
>
> $ echo 'export XYZ=ABC=' | sed 's/^\([^=]*\)=/\1:>>>/' | column -t -s '>>>'
> export XYZ:  ABC=
>
> In this case the = is preserved in the env var value. I'll check if this
> solves a bug I found and update the comment afterwards and possibly send a
> PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/184>.
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by robholland** [comment]
This was adjusted in: https://github.com/dokku-alt/dokku-alt/pull/191

As noted on that PR, column isn't actually using '>>>' but just '>'. It doesn't accept a sequence as an argument unfortunately. My PR replaced the '=' with '|' (pipe) which is slightly less likely to cause issues (I hope).

Sorry, I didn't notice this issue before.

**Comment by ayufan** [comment]
Thanks for help :)

**Comment by davidpelaez** [comment]
Hadn't noticed the update on this, thanks for the help!
