### ISSUE TITLE
Docker pull problems: Certificate is valid for ..., not index.docker.io

### ISSUE THREAD

**Issue by chmanie** [dokku-alt/dokku-alt#187]
Since upgrading to dokku-alt and docker to 1.5.0 (lxc-docker) via apt-get upgrade I am getting the following message when trying to pull an image:

Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate is valid for *.my-domain.com, my-domain.com, not index.docker.io

Where my-domain.com is actually the domain for my server.

A curl https://index.docker.io/v1/repositories/library/ubuntu/images on the host system works just fine.

Did I do something wrong or is this a dokku-alt or docker related issue?

**Comment by ayufan** [comment]
Intresting I did update test server and don't see such problem. Maybe you have something with DNS servers?

**Comment by chmanie** [comment]
It seems to be the lxc-docker package that causes errors. Is it possible to use dokku-alt with the standard docker.io package?

**Comment by ayufan** [comment]
Yes as long as you can use docker in shell. If I remember correctly docker.io uses docker.io as docker command.

**Comment by ayufan** [comment]
But I'm thinking about some rework which is now possible with introduction of docker rename in 1.5.0. It's finally possible to nicely support fig/compose :)

**Comment by chmanie** [comment]
That sounds good! Problem is if I install dokku-alt via apt-get it wants to remove docker.io and to install lxc-docker :(

**Comment by ayufan** [comment]
Please join. It'll be easier: https://gitter.im/dokku-alt/dokku-alt?utm_source=share-link&utm_medium=link&utm_campaign=share-link
