### ISSUE TITLE
413 “Request Entity Too Large” error with uploading a file

### ISSUE THREAD

**Issue by that0n3guy** [dokku-alt/dokku-alt#195]
This is an easy fix by adding something like `client_max_body_size 50M;` to my nginx.conf

How should I go about doing this?  Should this just be added into `/home/dokku/myapp/nginx.conf.d/whatever.conf`?

Will the folder home/dokku/myapp/nginx.conf.d get removed at any point (like rebuild/deplyments)?

**Comment by ayufan** [comment]
Nope. It's extract configuration that you can inject to nginx.

**Comment by that0n3guy** [comment]
> Nope

Nope the directory won't be deleted?

**Comment by ayufan** [comment]
Yes. It won't be touched.

**Comment by that0n3guy** [comment]
Ok... thanks.  Here are my docs (run as root):

```
mkdir /home/dokku/appname/nginx.conf.d/
echo 'client_max_body_size 50M;' > /home/dokku/appname/nginx.conf.d/upload.conf
chown dokku:dokku /home/dokku/appname/nginx.conf.d/upload.conf #I don't know if this is needed
service nginx reload
```
