### ISSUE TITLE
How to set a port that nginx points at (upstream)

### ISSUE THREAD

**Issue by that0n3guy** [dokku-alt/dokku-alt#197]
My nginx.conf looks like:

```
upstream site{ server 172.17.1.181:80; }
server {
  listen      [::]:80;
  listen      *:80;
  server_name site.docker.site.com;

  location    / {
    proxy_pass  http://site;
    ...
```

I would love it if I could set an upstream port like so (note `server 172.17.1.181:2368`): 

```
upstream site{ server 172.17.1.181:2368; }
server {
  listen      [::]:80;
  listen      *:80;
  server_name site.docker.site.com;

  location    / {
    proxy_pass  http://site;
    ...
```

How do I do this?

**Comment by ayufan** [comment]
It checks if image (buildstep or dockerfile) exposes one of the ports: 5000, 8080 or 80. It selects the first one as upstream port for server. You can add a port to list of exposed by adding to dokkurc:
```DOKKU_EXPOSED_PORTS="5000 8080 80 2368"```

It will use the 2368 if it's added as EXPOSE in Dockerfile.

**Comment by that0n3guy** [comment]
@ayufan that would expose 2368 directly though, correct?  I want to access my sites at port 80 with nginx proxying to 2368 in the container.

**Comment by ayufan** [comment]
What do you mean by directly?

To summarize:
Add to dokkurc:
```DOKKU_EXPOSED_PORTS="5000 8080 80 2368"```

And to Dockerfile:
```EXPOSE 2368```

It should be enough.

**Comment by that0n3guy** [comment]
I gotcha.   I was thinking that if I exposed 2368, I would have to go to `mysite.com:2368` to access it.   I just tested it... it does work as expected.

THANKS!

**Comment by ayufan** [comment]
Great to hear :)
