### ISSUE TITLE
Multiple domains, multiple SSL, single app

### ISSUE THREAD

**Issue by that0n3guy** [dokku-alt/dokku-alt#199]
I have a site that I just turned into a "multi-site" site.  Same codebase but can run off 2 different domains.

This normally wouldn't be a problem, but in this case, they both are ssl and both have different certs.

Anyway to do this without deploying to 2 different apps?

**Comment by ayufan** [comment]
So basically you need to have different pair of certs?

**Comment by that0n3guy** [comment]
Yup, and key.  Maybe something like: 
```
# this sets the same for 2 domains
cat ssl-bundle | dokku ssl:certificate myapp domain.com otherdomaon.com

#
cat ssl-bundle | dokku ssl:certificate myapp lastdomaon.com
```

**Comment by ayufan** [comment]
I thought about creating global certificate store and get certificates assigned automatically to apps, but for now you can make it by hand and have it still working :) but it's a little hackish.

Copy /home/dokku/myapp/nginx.conf to /etc/nginx/conf.d/myapp-with-second-certs.conf, edit this new file and reload nginx.

**Comment by ayufan** [comment]
And from the file remove upstream, because it's already defined by /home/dokku/myapp/nginx.conf.

**Comment by that0n3guy** [comment]
I gotcha.   Thanks.
