### ISSUE TITLE
Can't start container on dokku-alt (setuidgid: usage: setuidgid account child) but works on dokku

### ISSUE THREAD

**Issue by dj-hedgehog** [dokku-alt/dokku-alt#200]
I'm using this buildpack https://github.com/tonycoco/heroku-buildpack-ember-cli to deploy my container to dokku which works as it's supposed to.
I've got a second host running dokku-alt and deployed my Ember-CLI application there as well.
Upon start the only log-message I get via `dokku logs <container` is:
`setuidgid: usage: setuidgid account child`

Do you know what might be the problem or how I can get more information regarding this problem?

**Comment by cu12** [comment]
I'm experiencing the same, on a fresh dokku-alt environment with boxen-web, interestingly on another environment with the same version of the package (0.3.10-7-gf34bb41) it's working fine.

**Comment by snowping** [comment]
After upgrading to version 0.3.10-7-gf34bb41 I got the same error. Downgraded the debian package back to version 0.3.8-3-g1db9605 and now it's working again. I stay tuned :) hope someone here can help..

**Comment by ayufan** [comment]
@dj-hedgehog @snowping @cu12 can you guys post steps to reproduce the issue so I can get it easily fixed? :)

**Comment by cu12** [comment]
Hey, it turned out that my colleague forgot to commit the Procfile. So it was a missing Procfile in my case.

**Comment by ayufan** [comment]
Nice, but it should also handle case with default .release. So I need to check it anyway.

**Comment by snowping** [comment]
Haven't had time to look deeper into it yet, but what I can say so far is that I got this error with the following external buildpacks: 
- https://github.com/heroku/heroku-buildpack-java
- https://github.com/cloudfoundry-community/staticfile-buildpack.git

I can successfully deploy apps using those buildpacks with version 0.3.8-3-g1db9605. No procfile in root.

**Comment by ayufan** [comment]
Ok. I know why it doesn't work.

On Mon, Mar 2, 2015 at 11:04 PM, Joël <notifications@github.com> wrote:

> Haven't had time to look deeper into it yet, but what I can say so far is
> that I got this error with the following external buildpacks:
>
>    - https://github.com/heroku/heroku-buildpack-java
>    - https://github.com/cloudfoundry-community/staticfile-buildpack.git
>
> I can successfully deploy apps using those buildpacks with version
> 0.3.8-3-g1db9605. No procfile in root.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/200#issuecomment-76836292>.
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by paralin** [comment]
Still having this issue too. Any way to fix this?

**Comment by ayufan** [comment]
It's fixed.

Please redownload: ```docker pull ayufan/dokku-alt-buildstep:cedar-14``` and rebuild app.
