### ISSUE TITLE
Per App Admin Access

### ISSUE THREAD

**Issue by that0n3guy** [dokku-alt/dokku-alt#211]
I know this has been brought up before, but I really need per app admin access.

Essentially I have multiple developers from different companies.  I do not want developers from project A to be able to mess w/ project B.     This is sort of doable with deployment only keys, but is becoming a HUGE pane when they are trying to debug things.  If they could simply `ssh dokku@dokkusite.com enter appname` they could do their debugging much simpler.

I would also like them to be able to do something like `ssh dokku@dokkusite.com redis:delete appname` and `ssh dokku@dokkusite.com redis:create appname` (since redis is linked to the appname app).

Any ideas of how to do this?

**Comment by ayufan** [comment]
Allow to enter or exec is relatively easy to add, because everything is there. The problem is with other commands, but is still doable, but how it should work. `redis:create` operates not on `appname`, but `dbname`.

**Comment by ayufan** [comment]
We could add `developer` keys which would have more privileges.

**Comment by that0n3guy** [comment]
Yes.  It looks like it would be really easy to expand the `access` acl... something like this (below) would allow you to add an optional appname:

```
case "$1" in
  access:add)
    verify_max_args 2 "$@" # I changed max args to 2

    # check if arg 2 is set, if not.. act normal
    if [ -z ${2+x} ];
    then
      add_ssh_key "admin-$2"
      info "$FINGERPRINT added as an admin-$2"
    else
      add_ssh_key "admin"
      info "$FINGERPRINT added as an admin"
    fi
    ;;
```

Then in verify-command... do something like that:

```
# not real bash... just spit balling

if `$NAME` has `admin-` in it... 
then 
  APPNAME = eerything after `admin-` 

  # Allow normal git deploy stuff here
  
  if $APPNAME == $2
  then
    allow the command
  else
     fail 'command not allowed
  fi
fi
```

**Comment by ayufan** [comment]
It's not that simple, because verify-command works on commands not on APPNAME.

This would allow you to access single app per-key.

I still think that current deployment keys by adding FINGERPRINT to additional file that will mark it as key with elevated permission allowing to access some selected/filtered commands.

**Comment by that0n3guy** [comment]
Verify-command looks like it checks $NAME though... this name is either `admin` or `deploy`... right?

So if we make the $NAME something like `admin-appname` instead of just plain `admin` (set in `access:add` i think) then we can pull appname from $NAME by spitting after `admin-`..

**Comment by ayufan** [comment]
Yes. It checks, but with admin-appname it forces ssh key to be used only by single app and that I don't like.

**Comment by that0n3guy** [comment]
Oh I gotcha... I didn't think of that.  I was thinking you could set it multple times for the different apps, but I don't think you can since you can't sent the fingerprint more than once.

**Comment by ayufan** [comment]
Yes. Fingerprint is unique. Name is simply used to distinguish key type.

**Comment by that0n3guy** [comment]
So something very similar to how you did the `~dokku/appname/DEPLOY_ALLOWED` file, but have do something like (below) in verify-command:

```
#!/bin/bash

source "$(dirname $0)/vars"

cat

[[ -z "$NAME" ]] && [[ $(id -un) != "root" ]] && fail "Access denied. No user supplied."

# http://unix.stackexchange.com/a/67900
if [ "$NAME" != "developer" ] && [ "$NAME" != "deploy" ]; then
    # Allow everything
    exit 0
fi

[[ -z "$FINGERPRINT" ]] && fail "Access denied. No fingerprint supplied."

case "$1" in
    git-hook)
        APP="$2"
        ;;

    git-*)
        APP="$(echo "$2" | perl -pe 's/(?<!\\)'\''//g' | sed 's/\\'\''/'\''/g')"
        ;;

    *)
        if [[ "$NAME" == "developer" ]]; then
          APP="$2"
        else
          fail "Access denied. Please login as an admin."
        fi
        ;;
esac

check_app_name "$APP"

if ! is_fingerprint_allowed "$FINGERPRINT"
then
    fail "Access denied. You don't have permission to access this app."
fi
```

I tested the above by creating adding a deploy key, then manually changing my authorized_keys name to be developer instead of deploy... works well.

This allows you to just add the developer fingerprints the `DEPLOY_ALLOWED` file and it would work.  You may want a separate DEVELOPER_ALLOWED file though too.

**Comment by ayufan** [comment]
It's infact done. It's still requires some tests, but should work already :)
