### ISSUE TITLE
How to set port per app?

### ISSUE THREAD

**Issue by abrkn** [dokku-alt/dokku-alt#215]
I'd like to not use vhosts, but instead assign a port per app. There is no file at `/home/dokku/VHOST`, yet each app is set to be hosted at `appname.serverhostname`.

**Comment by ayufan** [comment]
`VHOST` is generated automatically. If you don't expose 5000, 8080 or 80 app will not have automatic nginx mapping. You can create `DOCKER_ARGS_WEB` in `/home/dokku/myapp` and add `-p port` as described in `docker run` help.
