### ISSUE TITLE
Expose multiple ports

### ISSUE THREAD

**Issue by paralin** [dokku-alt/dokku-alt#217]
Similar to #215 - how can I expose misc service ports? I host my app on port 80, and also on a random second port for the desktop client service.

I don't need the second port to be routed, even, just exposed on the host

**Comment by paralin** [comment]
Or is this the way it already works? My app might just not be accepting connections properly...

**Comment by paralin** [comment]
This means, in my app, I need an additional `-p` option in `docker run`

**Comment by ayufan** [comment]
Yes. Create `DOCKER_ARGS_WEB` in /home/dokku/myapp and add `-p port` there. As this is unsafe option it have to be done by hand.

**Comment by paralin** [comment]
Nice, thanks
