### ISSUE TITLE
Problem exposing the IP of the machine

### ISSUE THREAD

**Issue by Kikobeats** [dokku-alt/dokku-alt#233]
After a dokku-alt installation and putting some cointaniers I felt that the address of the machine is not exposed (but the port yes):

```bash
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS              PORTS               NAMES
9bb043653336        dokku/zombts:deployed             "/start"               6 days ago          Up 6 days           5000/tcp            app_zombts_1426962032_16369
9b98ea49b3b0        ayufan/dokku-alt-mongodb:latest   "/usr/bin/start_mong   6 days ago          Up 6 days           27017/tcp           mongodb_single_container
d2a5dcadd44a        dokku/kikobeats-blog:deployed     "/start"               7 days ago          Up 7 days           5000/tcp            app_kikobeats-blog_1426940104_29078
01c804801ca6        ayufan/dokku-alt-mariadb:latest   "/usr/bin/start_mari   7 days ago          Up 7 days           3306/tcp            mariadb_single_container
```

I don't know if is a particular problem. I have a fresh dropplet in DigitalOcean. 
This issure is related with [Can't make a remote connection @ mongodb plugin](https://github.com/jeffutter/dokku-mongodb-plugin/issues/46#issuecomment-87220898)

must be declared IP address configuration file somewhere that I forgot? There should be resolved automatically?

**Comment by ayufan** [comment]
It's expected. Nginx uses internal container networking. Such approach is securer (because on front there's only nginx) than publishing exposed ports to outside, becuase by default digital ocean machines doesn't have any firewall installed.
