### ISSUE TITLE
nginx ssl config defaults score low on globalsign SSL test.

### ISSUE THREAD

**Issue by rusintez** [dokku-alt/dokku-alt#237]
Hi guys, I've got a low score on SSL implementation test (https://sslcheck.globalsign.com/en_US/sslcheck?host=www.ploy.cc#178.62.207.32).
Default dokku-alt ssl configuration is used. Any idea on how could I update nginx config? Will there be a way to use custom nginx configuration (had seen it future plans)?

Thank you.

**Comment by jadsonlourenco** [comment]
Well first I think you are using Ubuntu 14.04 or Debian, so update the Nginx for last version with spdy module: https://kura.io/apt.kura.io/

And in each folder of an App has a **nginx.conf** file, that you can edit. Just see in "/home/dokku/app-name/nginx.conf". I hope this help you.

**Comment by rusintez** [comment]
thanks :+1: , ill try this now

**Comment by ayufan** [comment]
Yes. You can add additional config in nginx.conf.d folder, because nginx.conf is overwritten every deploy.

**Comment by rusintez** [comment]
Would i make sense to include projects own `.nginx.conf` if it's located in the root of the repo?

**Comment by ayufan** [comment]
Nope. It'll collide with nginx.conf generated automatically.

**Comment by rusintez** [comment]
let it collide then ? overwrite nginx.conf generated automatically with user's one? does this make sense? I'm using a scenario, where users don't have direct access to dokku-alt machine, but want to have custom nginx configs.

**Comment by ayufan** [comment]
Let's try to resolve issue: you want to have higher score in globalsign SSL?

**Comment by ayufan** [comment]
Comparision: https://sslcheck.globalsign.com/en_US/sslcheck?host=direct.ayufan.eu#94.23.217.159, https://www.ssllabs.com/ssltest/analyze.html?d=direct.ayufan.eu. I'm using latest dokku-alt-beta release.

**Comment by rusintez** [comment]
Yes :)
does it make sense to resolve https://sslcheck.globalsign.com/en_US/sslcheck?host=direct.ayufan.eu#94.23.217.159 issues and include them in default ssl nginx config?

**Comment by ayufan** [comment]
These are grades when installed dokku-alt-beta.

Kamil

On Monday, April 6, 2015, vlspopov <notifications@github.com> wrote:

> Yes :)
> does it make sense to resolve
> https://sslcheck.globalsign.com/en_US/sslcheck?host=direct.ayufan.eu#94.23.217.159
> issues and include them in default ssl nginx config?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/237#issuecomment-90015093>.
>


-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu
