### ISSUE TITLE
change mariadb config

### ISSUE THREAD

**Issue by cphubs** [dokku-alt/dokku-alt#239]
How can i change mariadb config file?

Thanks

**Comment by ayufan** [comment]
What do you need?

**Comment by cphubs** [comment]
I work on project with dokku-alt that my client should change common mysql settings like
Encoding - Max connections limit and ...

**Comment by ayufan** [comment]
It's possible. You have to:
```bash
git clone https://github.com/dokku-alt/mariadb-dockerfiles
# modify mariadb-dockerfiles (add configs, etc.)
docker build -t my-mariadb mariadb-dockerfiles
echo MARIADB_IMAGE=my-mariadb >> /home/dokku/.dokkurc
dokku mariadb:restart
```

**Comment by cphubs** [comment]
if possible make it as volume to edit config?
