### ISSUE TITLE
Welcome to nginx instead of serving the app

### ISSUE THREAD

**Issue by sochka** [dokku-alt/dokku-alt#242]
Hi, 

I'm trying to setup my docker app on Microsoft Azure Ubuntu VM instance.

`dokku logs wdc-app` shows

```
oleksandr@wdc-app:~$ dokku logs wdc-app
--------------------------------------------------------
:: Sun Apr 12 2015 02:44:53 GMT+0000 (UTC)
Environment : production
Host        : wdc-app.cloudapp.net
Port        : 80
--------------------------------------------------------

               .-..-.

   Sails              <|    .-..-.
   v0.11.0             |\
                      /|.\
                     / || \
                   ,'  |'  \
                .-'.-==|/_--'
                `--'-------' 
   __---___--___---___--___---___--___
 ____---___--___---___--___---___--___-__

Server lifted in `/app`
To see your app, visit http://wdc-app.cloudapp.net
To shut down Sails, press <CTRL> + C at any time.
```

But when I'm going to the link I see only

```
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.
```

Port 80 is opened correctly. My own app exposes port 8080 but according to the docs it should be routed by dokku-alt correctly to port 80.

Is it a bug in dokku-alt or I'm doing something wrong?

**Comment by sochka** [comment]
`docker ps` shows

```
oleksandr@wdc-app:~$ docker ps
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS              PORTS               NAMES
5c56be3c6a09        dokku/wdc-app:deployed            "node app.js --prod"   10 hours ago        Up 18 seconds       80/tcp              app_wdc-app_1428806686_19750   
5123080b0edb        ayufan/dokku-alt-mongodb:latest   "/usr/bin/start_mong   11 hours ago        Up 11 hours         27017/tcp           mongodb_single_container       
```

**Comment by sochka** [comment]
Just in case - there is no `VHOST` file at - `~dokku` but there is a `HOSTNAME` file there with `wdc-app.cloudapp.net` contents.

**Comment by sochka** [comment]
Ok, I was able to fix that. 

Initially I did `dokku domains:set wdc-app wdc-app.cloudapp.net:80`, fixed that with `dokku domains:set wdc-app wdc-app.cloudapp.net`.


Is it normal behaviour that previous two commands aren't identical?

**Comment by ayufan** [comment]
Yes, because you set hostname no listening address of server.

On Sun, Apr 12, 2015 at 4:04 PM, Oleksandr Sochka <notifications@github.com>
wrote:

> Ok, I was able to fix that.
>
> Initially I did dokku domains:set wdc-app wdc-app.cloudapp.net:80, fixed
> that with dokku domains:set wdc-app wdc-app.cloudapp.net.
>
> Is it normal behaviour that previous two commands aren't identical?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/242#issuecomment-92067557>.
>



-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by sochka** [comment]
I did, but the hostname was `wdc-app wdc-app.cloudapp.net:80` instead of `wdc-app wdc-app.cloudapp.net`
