### ISSUE TITLE
Run commands from the client

### ISSUE THREAD

**Issue by flaviobarros** [dokku-alt/dokku-alt#243]
I'm able to run commands from the server. BUT there is something like heroku toolbelt for dokku-alt?

**Comment by fizz** [comment]
I messed around with a bunch of clients/alternatives, this is what finally worked best: clone the original dokku project into ~/.dokku and add an alias to your shell: 
```bash 
alias dokku=$HOME/.dokku/contrib/dokku_client.sh
```
(dokku-alt includes an outdated contrib/dokku_client.sh that didn't work for me)

**Comment by flaviobarros** [comment]
Nice fizz! It's great.
