### ISSUE TITLE
"Path is forbidden" when creating host-based volume

### ISSUE THREAD

**Issue by jumski** [dokku-alt/dokku-alt#261]
Running:

```bash
$ dokku volume:create volume-name /data/test:/test
```

results in error:

```
/data/test:/test: Path is forbidden
```

I tried it both with existing and missing `/data/test` on host, but always get `Path is forbidden`.

Am i missing something?

Thanks

**Comment by jumski** [comment]
I was missing `To use this feature, you have to be logged as root and then simply type`

sorry about that, closing :)

**Comment by brunowego** [comment]
:+1:
