### ISSUE TITLE
elasticsearch plugin for dokku-alt?

### ISSUE THREAD

**Issue by npow** [dokku-alt/dokku-alt#45]
Is anyone using elasticsearch with dokku-alt? I tried using jedez/dokku-elasticsearch-plugin, but when I restarted my machine I'm getting the following error. Trying to figure out if it's an issue with the plugin or not..

```
2014/09/27 22:07:27 json: cannot unmarshal array into Go value of type map[string]interface {}
```

**Comment by jamespacileo** [comment]
@npow have you managed to sort it out in the end?
