### ISSUE TITLE
Invalid app name

### ISSUE THREAD

**Issue by yazinsai** [dokku-alt/dokku-alt#60]
I'm trying to create a root app for my domain `mydomain.com`. In Dokku, I would do this using (on my local machine):

``` bash
git remote add dokku dokku@mydomain.com:mydomain.com
git push remote master
```

This would create the app `mydomain.com` in Dokku, but I instead get this message:

``` bash
Invalid app name
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

How would I create a root domain when I can't specify a domain as the app name?

**Comment by alecgorge** [comment]
What is wrong with using periods in the app name? I realize Heroku doesn't allow this, but that doesn't feel like a good reason to prevent usage of periods in names.

**Comment by Dremora** [comment]
The original dokku allows periods. If they are present, application name becomes its fully qualified domain name, saving an extra configuration step. Would be nice to have this feature in dokku-alt as well.

**Comment by omeid** [comment]
+1 I don't see the advantage of adding an extra configuration step.
