### ISSUE TITLE
Problems when pushing after following readme.

### ISSUE THREAD

**Issue by paragonbliss** [dokku-alt/dokku-alt#79]
After following the readme and having set up a domain i get the following error.

```
fatal: 'node-js-app' does not appear to be a git repository
fatal: Could not read from remote repository.
```

Did not configure manually, but through the sinatra server method. 
Any insight on this?

**Comment by sedouard** [comment]
Ran into the same issue. opened a minor pull request to add this to the doc. https://github.com/dokku-alt/dokku-alt/pull/162

**Comment by MozMorris** [comment]
:+1:  @sedouard

**Comment by ValkyrieUK** [comment]
@sedouard :+1: I also made this mistake initially
