### ISSUE TITLE
Specific revision deploy?

### ISSUE THREAD

**Issue by romaninsh** [dokku-alt/dokku-alt#84]
Few questions. Through the use of dokku-alt in production environments, i've found few problems. Sometimes the deployed version contains a problem, and I need to "roll back" to another repository. If that would be an ordinary deploy, it would be as simple as "svn co <rev>".

Is it possible to instruct dokku to rebase using specific revision or branch?

Another question - dokku creates those instances in docker. After old ones are destroyed, can they still be restored somehow?

**Comment by romaninsh** [comment]
This works well, however when i do:

    git push production release-1.2

and release-1.2 being the current branch, the automatic rebuild does not start and requires me to manually rebuild.

    -----> WARNING: deploy did not complete, you must push to master.
    -----> for example, try 'git push <dokku> release-1.2:master'
    To dokku@production1.linkedfinance.com:lf
       fbd3432..96430fc  release-1.2 -> release-1.2

**Comment by ayufan** [comment]
When using `git push` you have to specify where you want to push `git push production release-1.2:master` is that case :)
